/// Structured device catalog for Brand → Model selection
class DeviceData {
  static const Map<String, List<String>> devices = {
    'Samsung': [
      'Galaxy S21',
      'Galaxy S22',
      'Galaxy S23',
      'Galaxy S24',
      'Galaxy S25',
      'Galaxy S26',
      'Galaxy M31',
      'Galaxy M32',
      'Galaxy M33',
      'Galaxy A52',
      'Galaxy A54',
      'Galaxy A55',
      'Galaxy A56',
      'Galaxy Z Fold 6',
      'Galaxy Z Flip 6',
    ],
    'Apple': [
      'iPhone 12',
      'iPhone 13',
      'iPhone 14',
      'iPhone 15',
      'iPhone 16',
      'iPhone 17',
      'iPhone 17 Pro',
      'iPhone 17 Pro Max',
      'iPhone SE (3rd Gen)',
    ],
    'Realme': [
      'Realme 8',
      'Realme 9',
      'Realme 10',
      'Realme 11',
      'Realme 12',
      'Realme 13',
      'Realme 14',
      'Realme GT',
      'Realme GT Neo',
      'Realme Narzo 70',
    ],
    'OnePlus': [
      'OnePlus 9 Pro',
      'OnePlus 10 Pro',
      'OnePlus 11',
      'OnePlus 12',
      'OnePlus 13',
      'OnePlus Nord 3',
      'OnePlus Nord 4',
      'OnePlus Nord CE 4',
      'OnePlus Open',
    ],
    'Xiaomi': [
      'Xiaomi 12 Pro',
      'Xiaomi 13 Pro',
      'Xiaomi 14',
      'Xiaomi 14 Ultra',
      'Xiaomi 15',
      'Xiaomi 15 Pro',
      'Xiaomi Mix Fold 4',
      'Xiaomi 13T',
    ],
    'Redmi': [
      'Redmi Note 11',
      'Redmi Note 12 Pro',
      'Redmi Note 13 Pro+',
      'Redmi Note 14 Pro+',
      'Redmi K70',
      'Redmi K80',
      'Redmi 12 5G',
      'Redmi 13C',
    ],
    'Vivo': [
      'Vivo X90 Pro',
      'Vivo X100 Pro',
      'Vivo X200',
      'Vivo V29',
      'Vivo V30 Pro',
      'Vivo V40 Pro',
      'Vivo T3 5G',
      'Vivo Y200',
    ],
    'Oppo': [
      'Oppo Find X6 Pro',
      'Oppo Find X7 Ultra',
      'Oppo Find N3',
      'Oppo Reno 10 Pro',
      'Oppo Reno 11 Pro',
      'Oppo Reno 12 Pro',
      'Oppo A78',
      'Oppo F25 Pro',
    ],
    'Motorola': [
      'Motorola Edge 40',
      'Motorola Edge 50 Pro',
      'Motorola Edge 50 Ultra',
      'Motorola Razr 50 Ultra',
      'Moto G84',
      'Moto G85',
      'Moto G64',
      'Moto G54',
    ],
    'Google Pixel': [
      'Pixel 6',
      'Pixel 6 Pro',
      'Pixel 7',
      'Pixel 7 Pro',
      'Pixel 7a',
      'Pixel 8',
      'Pixel 8 Pro',
      'Pixel 8a',
      'Pixel 9',
      'Pixel 9 Pro',
      'Pixel 9 Pro Fold',
    ],
  };

  /// Returns list of all available brand names
  static List<String> get brands => devices.keys.toList();

  /// Returns list of models for a specific brand
  static List<String> getModels(String brand) => devices[brand] ?? [];
}
